### ISSUE TITLE
Get acknowledged when we lost connection to the Rabbit server 

### ISSUE THREAD

**Issue by rerezML** [SpinGo/op-rabbit#101]
Hi,
Will it be possible to add an optional actor reference to the RabbitControl  that will be acknowledge when we are disconnected from the Rabbit server?
May be we already have it but I was unable to find.
The use case I have is that i need to alert my operator when the Rabbit is gone.
Thanks

**Comment by timcharper** [comment]
Hey @rerezML - If you look at https://github.com/SpinGo/op-rabbit/blob/v1.6.0/core/src/main/scala/com/spingo/op_rabbit/RabbitControl.scala#L37, there's a command to get a reference to the underlying akka-rabbitmq actor. Once you get a reference to that connection actor, everything at https://github.com/thenewmotion/akka-rabbitmq applies.

Here's some psuedo code to help point you in the direction:

```
import akka.pattern.ask
import scala.concurrent.duration._
import scala.concurrent.Await

implicit val timeout = akka.util.Timeout(1.seconds)
val connectionActor = Await.result(
  (rabbitControl ? RabbitControl.GetConnectionActor).mapTo[ActorRef],
  5.seconds)
```

When designing this library I felt it would be better to embrace and build on top of existing abstractions rather than reinvent the wheel.

**Comment by rerezML** [comment]
Hi Tim,
Thanks a lot for your quick answer.
I will look into it.
Thanks again.
