### ISSUE TITLE
Scala 2.10 cross build

### ISSUE THREAD

**Issue by kiequoo** [SpinGo/op-rabbit#43]
Hi Tim,

I have a (private) lib I am developing and am using op-rabbit.  I want it cross build for scala 2.10 and 2.11 still, so set up my sbt accordingly.  I was hoping that the v1.0.x branch of op-rabbit would cross build for scala 2.10, and it seems it is set up to cross build in build.sbt.  However I don't see a published release of 1.0.3 for scala 2.10 and when I tried to compile it myself there was a dependency problem.  So my question is, do you still plan to support scala 2.10 in the v1.0.x branch? :)

Thanks
Dan

**Comment by timcharper** [comment]
Sure, no problem. I don't think there is any reason why we can't do across build.

**Comment by timcharper** [comment]
So, bummer! Can't do it for the v1.1.x branch. Akka 2.4.0 dropped support for Scala 2.10. I'll try for the v1.0.x branch, however. It wouldn't be too hard to back port a handful of the changes, but some features in `v1.1.x` branch rely on features of `Akka 2.4.0` (the subscription management actor is significantly better due to improved FSM transition support).

**Comment by timcharper** [comment]
v1.0.4 is published with scala support. I can't push the acked-stream 1.0 dependency to maven central right now because they're having issues, but I pushed a copy to the SpinGo s3 repo temporarily.
