### ISSUE TITLE
autoack support?

### ISSUE THREAD

**Issue by anthonylau** [SpinGo/op-rabbit#56]
Would there be autoack support in the future?

**Comment by timcharper** [comment]
I'm not against it, but I'm not sure how it would be best implemented. A lot of the library depends on acking. What's your use case? How would autoack support help? If the answer is "speed" then you should probably just use the raw driver because op-rabbit places an emphasis on correctness, and not necessarily performance.

**Comment by anthonylau** [comment]
I'm exploring [Direct reply-to](https://www.rabbitmq.com/direct-reply-to.html) for RPC which requires no-ack mode. At the moment, I bind raw driver's consumer with op-rabbit. Just curious if there is native support.

**Comment by timcharper** [comment]
I'm unlikely to implement this; PR welcome.
