### ISSUE TITLE
Add option to bind queue/exchange passively

### ISSUE THREAD

**Issue by ghost** [SpinGo/op-rabbit#7]
Currently, binding to a queue (or exchange) that doesn't exist will create it. In some cases, though, it is preferable to fail if it doesn't exist. This can be accomplished by using queueDeclarePassive instead of queueDeclare.

(As a side note, I figured I'd try opening issues here instead of communicating through the user group topic. Which do you prefer?)

**Comment by timcharper** [comment]
Here, definitely. These discussions are, in theory, easier to find for the general public.

This is a good idea, and probably best achievable by creating additional subscription strategies. The Subscription class has an `initialized` future which could be used to communicate failure to bind.

**Comment by ghost** [comment]
I added support for passive bindings, but now it just keeps failing and retrying (without even pausing). However, I think this is a separate issue of how to handle subscription failures. The same problem can occur with the existing bindings if you try to bind to an existing queue with "wrong" parameters (durability, auto-delete, etc.).

**Comment by unthingable** [comment]
FWIW, this incessant retrying behavior has caused me some grief today as well.

My use case is the opposite of @talp-traiana: I want to use an existing non-autodelete queue if it exists, or create an autodelete one if it doesn't (because the client app is a good citizen); but the effect is the same. Would really like to be able to control the binding behavior and handle failures explicitly.

**Comment by timcharper** [comment]
@unthingable It sounds to me like you'd like to do a custom binding, or compose bindings together using something like an `orElse` operator?

I'm not happy with the present passing of error-logging et. al via implicits on the consumer binding, and am planning to change it. After that point, it'll be easier to define custom bindings.

**Comment by unthingable** [comment]
@timcharper I'd like to at least be able to check for queue presence and handle binding error explicitly. Doing it the opinionated way would require supporting at least three clearly selectable behaviors:
1. Expect the queue to exist, fail otherwise (@talp-traiana's case)
2. Expect the queue to _not_ exist, fail otherwise
3. Use the queue if it exists (ignoring supplied parameters), otherwise create with supplied parameters.

In general, setting up queues and bindings is too a nontrivial affair to wrap all of that in something like a single `topic()` or even `queue()` directive. I can see their intent of making things easy, but in practice they are having to make too many decisions to cover enough use cases.

**Comment by timcharper** [comment]
FYI - @talp-traiana the above patch, slated for M12 release, addresses the infinite retry. Retry will only occur on connection errors.

**Comment by timcharper** [comment]
FYI - M12 release went out. https://github.com/SpinGo/op-rabbit/compare/v1.0.0-M11...v1.0.0-M12

**Comment by timcharper** [comment]
Marking as resolved, since this now supported.

@unthingable can you open up an additional issue for your request?
