### ISSUE TITLE
Readme refers to wrong connection timeout property

### ISSUE THREAD

**Issue by ahmetsevki** [SpinGo/op-rabbit#73]
README.md has the following:
op-rabbit {
  topic-exchange-name = "amq.topic"
  connection {
    virtual-host = "/"
    hosts = ["127.0.0.1"]
    username = "guest"
    password = "guest"
    port = 5672
    ssl = false
    timeout = 3s
  }
}

However, the ConnectionParams.scala uses "connection-timeout" as the config key.
connectionTimeout = config.getDuration("connection-timeout", java.util.concurrent.TimeUnit.MILLISECONDS).toInt,

**Comment by matanox** [comment]
To the same overall topic the README example configuration implies (to the best of my understanding) creating a new exchange, whereas many users come here to connect to an existing one, something that the configuration syntax does not make entirely transparent.

**Comment by timcharper** [comment]
Thanks for this! Can you update the README and send a pull request?

**Comment by matanox** [comment]
I will do my best, the readme needs a lot of love I'll try something once things settle down. Had some terrible trouble connecting to a 2.8 rabbit broker, connection would die out without any notice nor reconnect. Maybe it was due to a mix of config and explicit connection factory options, not sure yet.

**Comment by timcharper** [comment]
fixed with 6e4c300
